channels:
 - bioconda
 - conda-forge
 - r
 - default
dependencies:
 - python=3.7
 - snakemake
 - bowtie2
 - pysam
 - samtools
 - blast
 - prokka
 - awscli
 - hs-blastn
 - biopython
 - numpy
 - r-essentials
 - r-base
 - r-tidyverse
