{% set name = "midas2" %}
{% set version = "0.9.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/1e/28/b235d50f5fb47b1af3142aaf168f765af53b3b5789af5a9c1f298c9e30e8/midas2-0.9.4.tar.gz
  sha256: fb4175c9b18fccba351fe77c1c10198ef6d107df4ff11d3ac8e815805cfd3758
  #git_url: https://github.com/czbiohub/MIDAS2.0.git
  #git_rev: v0.91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-dependencies

requirements:
  host:
    - python >=3.7,<3.8
    - pip
    - setuptools
  run:
    - python >=3.7,<3.8
    - tbb ==2020.2
    - numpy >=1.19.1
    - biopython >=1.79
    - gffutils >=0.10.1
    - bowtie2 >=2.4.5
    - samtools >=1.13
    - pysam >=0.18.0
    - hs-blastn ==0.0.5
    - blast >=2.12.0
    - awscli
    - lz4
    - prokka >=1.14.6
    - vsearch >=2.21.1

test:
  imports:
    - midas2
  commands:
    - midas2 --version
    - midas2 run_snps --help

about:
  home: "https://github.com/czbiohub/MIDAS2.0"
  license: MIT License
  license_family: MIT
  summary: "Metagenomic Intra-Species Diversity Analysis 2.0"
