{% set name = "midas2" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/1f/09/354dd2271184bc006e0eaa4340b25cdceab60fd855f726e5bd0fcb12802c/midas2-1.0.0.tar.gz
  sha256: c65500be5beb1c7c77288f2ae73ea2b49d443e9d42937cec28bf3bde6147fe0a
  #git_url: https://github.com/czbiohub/MIDAS2.0.git
  #git_rev: v0.91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-dependencies

requirements:
  host:
    - python >=3.7,<3.8
    - pip
    - setuptools
  run:
    - python >=3.7,<3.8
    - tbb ==2020.2
    - numpy >=1.19.1
    - biopython >=1.79
    - gffutils >=0.10.1
    - bowtie2 >=2.4.5
    - samtools >=1.13
    - pysam >=0.18.0
    - hs-blastn ==0.0.5
    - blast >=2.12.0
    - awscli
    - lz4
    - prokka >=1.14.6
    - vsearch >=2.21.1

test:
  imports:
    - midas2
  commands:
    - midas2 --version
    - midas2 run_snps --help

about:
  home: "https://github.com/czbiohub/MIDAS2"
  license: MIT License
  license_family: MIT
  summary: "Metagenomic Intra-Species Diversity Analysis 2"
